url: http://ggentili.github.io
baseurl: 

# Site settings
title: Rete Famiglie Adottive
email: rete.famiglie.adottive@gmail.com
description: "Sito ufficiale dell’Associazione Rete Famiglie Adottive"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 35aefe
  aa_primary: fed136
  secondary: 027cfe
  aa_secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: A
  pic: 1
  position: in A
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: B
  pic: 2
  position: in B
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: C
  pic: 3
  position: in C
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/ggentili
  - title: facebook
    url: https://www.facebook.com/retefamiglieadottive
  - title: email
    url: mailto:rete.famiglie.adottive@gmail.com
    
# Postal address (add as many lines as necessary)
address:
  - line: Perugia, Umbria
  - line: rete.famiglie.adottive@gmail.com
  - line: 

# Build settings
markdown: kramdown
permalink: pretty

